// Code generated by MockGen. DO NOT EDIT.
// Source: server.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	app "github.com/sealtv/worldofwisdom/internal/app"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ProcessClient mocks base method.
func (m *MockService) ProcessClient(c app.Clienter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessClient", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessClient indicates an expected call of ProcessClient.
func (mr *MockServiceMockRecorder) ProcessClient(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessClient", reflect.TypeOf((*MockService)(nil).ProcessClient), c)
}
